### ISSUE TITLE
https://prod.liveshare.vsengsaas.visualstudio.com/join?CE0F6A1E21D498D5A13576BB18B3C64AFC6A

### ISSUE THREAD

**Issue by josephworks** [josephworks/csharp#11]
https://prod.liveshare.vsengsaas.visualstudio.com/join?CE0F6A1E21D498D5A13576BB18B3C64AFC6A

**Comment by jkhack46** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?E1BFBB40619922C3D74DBC8E3EDDFEA3F692
