### ISSUE TITLE
crap

### ISSUE THREAD

**Issue by kwfer377** [josephworks/csharp#13]
JOSEPH YOUR CODE IS BROKEN 
ALSO FIX THE DAYLIGHT CYCLE ON YOUR MINECRAFT SERVER
![image](https://user-images.githubusercontent.com/54115091/70545655-29f9c580-1b2b-11ea-895e-7ccf91145fe9.png)

**Comment by kwfer377** [comment]
sorry

**Comment by josephworks** [comment]
@MrClarkeSoftware help plz

**Comment by josephworks** [comment]
This project "ChessGame" Has been temporarirailiarailiarirailary abandoned, therefore this issue does not need to be fixed yet.
